name: tv_channel_widget
description: ChannelWidget is inspired by Amazon Prime / Jio Tv and fully developed in dart with â¤ï¸ from scratch. Supports all the platfrom.
version: 0.0.1
repository: https://github.com/jigarfumakiya/tv_channel_widget
homepage: https://github.com/jigarfumakiya/tv_channel_widget

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  data_table_2: ^2.6.0
  flutter:
    sdk: flutter
  indexed_list_view: ^4.0.0
  intl: ^0.18.0
  linked_scroll_controller: ^0.2.0
  scrollable_positioned_list: ^0.3.8
  scrollable_positioned_list_extended: ^0.3.9
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

